test 2

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -22,6 +22,22 @@ jobs:
         run : make format
       - name: Lint
         run: make lint
+      - name: Archive and Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: ml_pipeline-artifacts
+          path: ${{ github.workspace }}
+        
+      - name: Save to repository
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          echo GH_TOKEN: "${GH_TOKEN}"
+          git config --global user.name 'github-actions'
+          git config --local user.email "action@github.com"
+          git add .
+          git commit -m "Added Results" || echo "ignore commit failure, proceed"
+          git push
       - name: Publish Artifact
         uses: actions/upload-artifact@v2
         with:
@@ -38,3 +54,4 @@ jobs:
       with:
         name: my-artifact
         path: downloaded-artifact
+    
