modifed main and cicd.yml ```

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,26 +1,31 @@
-name: CI
-
+name: CI/CD
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-  workflow_dispatch:
-
+env:
+  CARGO_TERM_COLOR: always
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name : install packages
-        run : make install
-      - name: test
-        run: make test
-      - name : format
-        run : make format
-      - name: lint
-        run: make lint
-      - name: Archive and Upload Artifacts
+    - uses: actions/checkout@v3
+    - uses: actions-rs/toolchain@v1
+      with:
+          toolchain: stable
+          profile: minimal
+          components: clippy, rustfmt
+          override: true
+    - name: build Rust
+      run: make build
+    - name: Format
+      run: make format
+    - name: Lint
+      run: make lint
+    - name: Test
+      run: make test
+    - name: Archive and Upload Artifacts
         uses: actions/upload-artifact@v3
         with:
           name: ml_pipeline-artifacts
@@ -33,8 +38,17 @@ jobs:
           echo GH_TOKEN: "${GH_TOKEN}"
           git config --global user.name 'github-actions'
           git config --local user.email "action@github.com"
-          git add .
-          git commit -m "Added Results" || echo "ignore commit failure, proceed"
-          git push
-          
-      
+          git add main/test/target/release/main
+          git commit -m "Added Executable" || echo "ignore commit failure, proceed"
+          git push 
+    
+
+  deploy:
+    needs: build
+    steps:
+    - uses: actions/checkout@v3
+
+    - uses: actions/upload-artifact@v3
+      with:
+        name: Rust Binary
+        path: main/test/target/release/main
